[package]
name = "rustls-native-certs"
version = "0.5.0"
edition = "2018"
authors = ["Joseph Birr-Pixton <jpixton@gmail.com>"]
license = "Apache-2.0/ISC/MIT"
readme = "README.md"
description = "rustls-native-certs allows rustls to use the platform native certificate store"
homepage = "https://github.com/ctz/rustls-native-certs"
repository = "https://github.com/ctz/rustls-native-certs"
categories = ["network-programming", "cryptography"]

[dependencies]
rustls-pemfile = "0.2"
log = { version = "0.4", optional = true }
rustls = { version = "0.20", optional = true }
webpki = { version = "0.22", optional = true }

[dev-dependencies]
ring = "0.16.5"
rustls = "0.20"
untrusted = "0.7.0"
webpki = "0.22"
webpki-roots = "0.22"

[features]
default = ["rustls", "webpki"]
logging = ["log"]

[[test]]
name = "smoketests"
required-features = ["rustls"]

[[test]]
name = "compare_mozilla"
required-features = ["webpki"]

[[example]]
name = "google"
required-features = ["rustls"]

[target.'cfg(windows)'.dependencies]
schannel = "0.1.15"

[target.'cfg(all(unix, not(target_os = "macos")))'.dependencies]
openssl-probe = "0.1.2"

[target.'cfg(target_os = "macos")'.dependencies]
security-framework = "2.0.0"
